--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Heisenburger69/BurgerLootProtection
build-by-default: true
branches:
  - master
projects:
  BurgerLootProtection:
    path: ""
    icon: loot.png
    libs:
      - src: JackMD/UpdateNotifier/UpdateNotifier
        version: ^1.0.0
...
