# You can enable and disable protection for item drops on death globally by toggling this setting.
enable-protection: true

# This is the amount of time in seconds that drops are protected and can only be picked up by the killer.
# After this time, anyone can pick up the items dropped.
protection-time: 15

# Set this to true if you want to use the blacklisted-worlds settings.
# If both enable-world-blacklist and disable-world-blacklist are set to the same setting,
# drop protection on death will be enabled for all words.
enable-world-blacklist: false

# If enable-world-blacklist is set to true, drop protection on death will be enabled for all worlds,
# except the worlds mentioned here.
blacklisted-worlds:
  - blacklistedworld1
  - blacklistedworld2

# Set this to true if you want to use the whitelisted-worlds settings
enable-world-whitelist: false

# If enable-world-whitelist is set to true, drop protection on death will be disabled for all worlds,
# except the worlds mentioned here.
whitelisted-worlds:
  - whitelistedworld1
  - whitelistecworld2

# When this is enabled, player's who try to pickup protected drops are sent a message telling them they cannot do so.
enable-protection-message: true

# This is the message sent to players when they try to pick up a protected item.
# The time left before the item becomes unprotected is replaced by {TIME}.
# You may use the symbol & for color codes.
protection-message: "&cYou cannot pick up this item for {TIME} seconds"

